# -*- coding: utf-8 -*-
"""bank scoring.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1bkIrm3MVi4xecEsbn3XvDZTK2KvcbHOG
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

X_train= pd.read_csv('/content/X_train.csv')
X_test= pd.read_csv('/content/X_test.csv')
y_train= pd.read_csv('/content/y_train.csv')
y_test= pd.read_csv('/content/y_test_sample.csv')

frames = [X_train, y_train]

df_train = pd.concat(frames, axis= 1)

df_train.head(60)

frames1 = [X_test, y_test.drop('index', axis=1)]

df_test = pd.concat(frames1, axis= 1)

df_test.head()

df_train.info()

df_train.describe()

df_train.dtypes

cr = df_train.corr()

cr_df_train = cr['target'].sort_values(ascending=False)
cr_df_train

sns.heatmap(df_train.corr())

df_train.isnull().sum()

df_train['monthly_income'].fillna(df_train['monthly_income'].median().round(0),inplace=True)

df_train.head()

df_train['family_members'].fillna(df_train['family_members'].mean().round(0),inplace=True)

df_train.isnull().sum()

cr = df_train.corr()

cr_df_train = cr['target'].sort_values(ascending=False)
cr_df_train

df_train.hist(bins=20, figsize =(15,10), color= 'blue', edgecolor='yellow')

df_train['target'].value_counts()

df_train['overdue_30_59_days'].unique()

df_train['overdue_60_89_days'].unique()

df_train['overdue__more_than_90_days'].unique()

df_train['mortgage_loans'].unique()

